/** Code auto-generated by cOde 1.1.1 **/
#include <R.h> 
 #include <math.h> 

static double parms[126];
static double forc[0];
static double cons[0];
static double range[2];

#define nGridpoints 2 
#define nSplines 0 
#define precision 1e-05 

#define k_P parms[0] 
 #define k_IM_1 parms[1] 
 #define ligand parms[2] 
 #define k_B parms[3] 
 #define k_E parms[4] 
 #define k_IM_3 parms[5] 
 #define k_I parms[6] 
 #define k_PM_4 parms[7] 
 #define k_D parms[8] 
 #define k_I_lig parms[9] 
 #define k_PM_4_lig parms[10] 
 #define k_D_lig parms[11] 
 #define y0_0 parms[12] 
 #define y1_0 parms[13] 
 #define y2_0 parms[14] 
 #define y3_0 parms[15] 
 #define y4_0 parms[16] 
 #define y5_0 parms[17] 
 #define y6_0 parms[18] 
 #define y7_0 parms[19] 
 #define y8_0 parms[20] 
 #define y9_0 parms[21] 
 #define y10_0 parms[22] 
 #define y11_0 parms[23] 
 #define y12_0 parms[24] 
 #define y13_0 parms[25] 
 #define y14_0 parms[26] 
 #define y15_0 parms[27] 
 #define y16_0 parms[28] 
 #define y17_0 parms[29] 
 #define y18_0 parms[30] 
 #define y19_0 parms[31] 
 #define y20_0 parms[32] 
 #define y21_0 parms[33] 
 #define y22_0 parms[34] 
 #define y23_0 parms[35] 
 #define y24_0 parms[36] 
 #define y25_0 parms[37] 
 #define y26_0 parms[38] 
 #define y27_0 parms[39] 
 #define y28_0 parms[40] 
 #define y29_0 parms[41] 
 #define y30_0 parms[42] 
 #define y31_0 parms[43] 
 #define y32_0 parms[44] 
 #define y33_0 parms[45] 
 #define y34_0 parms[46] 
 #define y35_0 parms[47] 
 #define y36_0 parms[48] 
 #define y37_0 parms[49] 
 #define y38_0 parms[50] 
 #define y39_0 parms[51] 
 #define y40_0 parms[52] 
 #define y41_0 parms[53] 
 #define y42_0 parms[54] 
 #define y43_0 parms[55] 
 #define y44_0 parms[56] 
 #define y45_0 parms[57] 
 #define y46_0 parms[58] 
 #define y47_0 parms[59] 
 #define y48_0 parms[60] 
 #define y49_0 parms[61] 
 #define y50_0 parms[62] 
 #define y51_0 parms[63] 
 #define y52_0 parms[64] 
 #define y53_0 parms[65] 
 #define y54_0 parms[66] 
 #define y55_0 parms[67] 
 #define y56_0 parms[68] 
 #define y57_0 parms[69] 
 #define y58_0 parms[70] 
 #define y59_0 parms[71] 
 #define y60_0 parms[72] 
 #define y61_0 parms[73] 
 #define y62_0 parms[74] 
 #define y63_0 parms[75] 
 #define y64_0 parms[76] 
 #define y65_0 parms[77] 
 #define y66_0 parms[78] 
 #define y67_0 parms[79] 
 #define y68_0 parms[80] 
 #define y69_0 parms[81] 
 #define y70_0 parms[82] 
 #define y71_0 parms[83] 
 #define y72_0 parms[84] 
 #define y73_0 parms[85] 
 #define y74_0 parms[86] 
 #define y75_0 parms[87] 
 #define y76_0 parms[88] 
 #define y77_0 parms[89] 
 #define y78_0 parms[90] 
 #define y79_0 parms[91] 
 #define y80_0 parms[92] 
 #define y81_0 parms[93] 
 #define y82_0 parms[94] 
 #define y83_0 parms[95] 
 #define y84_0 parms[96] 
 #define y85_0 parms[97] 
 #define y86_0 parms[98] 
 #define y87_0 parms[99] 
 #define y88_0 parms[100] 
 #define y89_0 parms[101] 
 #define y90_0 parms[102] 
 #define y91_0 parms[103] 
 #define y92_0 parms[104] 
 #define y93_0 parms[105] 
 #define y94_0 parms[106] 
 #define y95_0 parms[107] 
 #define y96_0 parms[108] 
 #define y97_0 parms[109] 
 #define y98_0 parms[110] 
 #define y99_0 parms[111] 
 #define y100_0 parms[112] 
 #define y101_0 parms[113] 
 #define y102_0 parms[114] 
 #define y103_0 parms[115] 
 #define y104_0 parms[116] 
 #define y105_0 parms[117] 
 #define y106_0 parms[118] 
 #define y107_0 parms[119] 
 #define y108_0 parms[120] 
 #define y109_0 parms[121] 
 #define y110_0 parms[122] 
 #define y111_0 parms[123] 
 #define y112_0 parms[124] 
 #define y113_0 parms[125] 
#define tmin range[0]
#define tmax range[1]


void x_s_initmod(void (* odeparms)(int *, double *)) {
	 int N=126;
	 odeparms(&N, parms);
}

void x_s_initforc(void (* odeforcs)(int *, double *)) {
	 int N=0;
	 odeforcs(&N, forc);
}

/** Derivatives (ODE system) **/
void x_s_derivs (int *n, double *t, double *y, double *ydot, double *RPAR, int *IPAR) {

	 double time = *t;

	 ydot[0] = 1.0*(k_P/(1.0+k_IM_1*(y[3]+y[5]*ligand)))-1.0*(k_B*y[0])-1.0*(k_E*y[0]/(1.0+k_IM_3*(y[3]+y[5]*ligand)));
 	 ydot[1] = 1.0*(k_E*y[0]/(1.0+k_IM_3*(y[3]+y[5]*ligand)))-1.0*(k_E*y[1]);
 	 ydot[2] = 1.0*(k_E*y[1])-1.0*(k_E*y[2]);
 	 ydot[3] = 1.0*(k_E*y[2])-1.0*(k_I*y[3])+1.0*(k_PM_4*y[4]);
 	 ydot[4] = 1.0*(k_I*y[3])-1.0*(k_PM_4*y[4])-1.0*(k_D*y[4]);
 	 ydot[5] = -1.0*(k_I_lig*y[5]*ligand)+1.0*(k_PM_4_lig*y[6]*ligand);
 	 ydot[6] = 1.0*(k_I_lig*y[5]*ligand)-1.0*(k_PM_4_lig*y[6]*ligand)-1.0*(k_D_lig*y[6]*ligand);
 	 ydot[7] = (-(k_B+k_E/(1.0+k_IM_3*(y[3]+y[5]*ligand))))*(y[7])+(-(k_P*k_IM_1/pow((1.0+k_IM_1*(y[3]+y[5]*ligand)),2.0)-k_E*y[0]*k_IM_3/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(y[10])+(-(k_P*(k_IM_1*ligand)/pow((1.0+k_IM_1*(y[3]+y[5]*ligand)),2.0)-k_E*y[0]*(k_IM_3*ligand)/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(0.0);
 	 ydot[8] = (k_E/(1.0+k_IM_3*(y[3]+y[5]*ligand)))*(y[7])+(-k_E)*(y[8])+(-(k_E*y[0]*k_IM_3/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(y[10])+(-(k_E*y[0]*(k_IM_3*ligand)/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(0.0);
 	 ydot[9] = (k_E)*(y[8])+(-k_E)*(y[9]);
 	 ydot[10] = (k_E)*(y[9])+(-k_I)*(y[10])+(k_PM_4)*(y[11]);
 	 ydot[11] = (k_I)*(y[10])+(-(k_PM_4+k_D))*(y[11]);
 	 ydot[12] = (-(k_B+k_E/(1.0+k_IM_3*(y[3]+y[5]*ligand))))*(y[12])+(-(k_P*k_IM_1/pow((1.0+k_IM_1*(y[3]+y[5]*ligand)),2.0)-k_E*y[0]*k_IM_3/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(y[15])+(-(k_P*(k_IM_1*ligand)/pow((1.0+k_IM_1*(y[3]+y[5]*ligand)),2.0)-k_E*y[0]*(k_IM_3*ligand)/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(0.0);
 	 ydot[13] = (k_E/(1.0+k_IM_3*(y[3]+y[5]*ligand)))*(y[12])+(-k_E)*(y[13])+(-(k_E*y[0]*k_IM_3/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(y[15])+(-(k_E*y[0]*(k_IM_3*ligand)/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(0.0);
 	 ydot[14] = (k_E)*(y[13])+(-k_E)*(y[14]);
 	 ydot[15] = (k_E)*(y[14])+(-k_I)*(y[15])+(k_PM_4)*(y[16]);
 	 ydot[16] = (k_I)*(y[15])+(-(k_PM_4+k_D))*(y[16]);
 	 ydot[17] = (-(k_B+k_E/(1.0+k_IM_3*(y[3]+y[5]*ligand))))*(y[17])+(-(k_P*k_IM_1/pow((1.0+k_IM_1*(y[3]+y[5]*ligand)),2.0)-k_E*y[0]*k_IM_3/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(y[20])+(-(k_P*(k_IM_1*ligand)/pow((1.0+k_IM_1*(y[3]+y[5]*ligand)),2.0)-k_E*y[0]*(k_IM_3*ligand)/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(0.0);
 	 ydot[18] = (k_E/(1.0+k_IM_3*(y[3]+y[5]*ligand)))*(y[17])+(-k_E)*(y[18])+(-(k_E*y[0]*k_IM_3/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(y[20])+(-(k_E*y[0]*(k_IM_3*ligand)/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(0.0);
 	 ydot[19] = (k_E)*(y[18])+(-k_E)*(y[19]);
 	 ydot[20] = (k_E)*(y[19])+(-k_I)*(y[20])+(k_PM_4)*(y[21]);
 	 ydot[21] = (k_I)*(y[20])+(-(k_PM_4+k_D))*(y[21]);
 	 ydot[22] = (-(k_B+k_E/(1.0+k_IM_3*(y[3]+y[5]*ligand))))*(y[22])+(-(k_P*k_IM_1/pow((1.0+k_IM_1*(y[3]+y[5]*ligand)),2.0)-k_E*y[0]*k_IM_3/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(y[25])+(-(k_P*(k_IM_1*ligand)/pow((1.0+k_IM_1*(y[3]+y[5]*ligand)),2.0)-k_E*y[0]*(k_IM_3*ligand)/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(0.0);
 	 ydot[23] = (k_E/(1.0+k_IM_3*(y[3]+y[5]*ligand)))*(y[22])+(-k_E)*(y[23])+(-(k_E*y[0]*k_IM_3/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(y[25])+(-(k_E*y[0]*(k_IM_3*ligand)/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(0.0);
 	 ydot[24] = (k_E)*(y[23])+(-k_E)*(y[24]);
 	 ydot[25] = (k_E)*(y[24])+(-k_I)*(y[25])+(k_PM_4)*(y[26]);
 	 ydot[26] = (k_I)*(y[25])+(-(k_PM_4+k_D))*(y[26]);
 	 ydot[27] = (-(k_B+k_E/(1.0+k_IM_3*(y[3]+y[5]*ligand))))*(y[27])+(-(k_P*k_IM_1/pow((1.0+k_IM_1*(y[3]+y[5]*ligand)),2.0)-k_E*y[0]*k_IM_3/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(y[30])+(-(k_P*(k_IM_1*ligand)/pow((1.0+k_IM_1*(y[3]+y[5]*ligand)),2.0)-k_E*y[0]*(k_IM_3*ligand)/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(0.0);
 	 ydot[28] = (k_E/(1.0+k_IM_3*(y[3]+y[5]*ligand)))*(y[27])+(-k_E)*(y[28])+(-(k_E*y[0]*k_IM_3/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(y[30])+(-(k_E*y[0]*(k_IM_3*ligand)/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(0.0);
 	 ydot[29] = (k_E)*(y[28])+(-k_E)*(y[29]);
 	 ydot[30] = (k_E)*(y[29])+(-k_I)*(y[30])+(k_PM_4)*(y[31]);
 	 ydot[31] = (k_I)*(y[30])+(-(k_PM_4+k_D))*(y[31]);
 	 ydot[32] = (-(k_B+k_E/(1.0+k_IM_3*(y[3]+y[5]*ligand))))*(y[32])+(-(k_P*k_IM_1/pow((1.0+k_IM_1*(y[3]+y[5]*ligand)),2.0)-k_E*y[0]*k_IM_3/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(y[35])+(-(k_P*(k_IM_1*ligand)/pow((1.0+k_IM_1*(y[3]+y[5]*ligand)),2.0)-k_E*y[0]*(k_IM_3*ligand)/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(y[37]);
 	 ydot[33] = (k_E/(1.0+k_IM_3*(y[3]+y[5]*ligand)))*(y[32])+(-k_E)*(y[33])+(-(k_E*y[0]*k_IM_3/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(y[35])+(-(k_E*y[0]*(k_IM_3*ligand)/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(y[37]);
 	 ydot[34] = (k_E)*(y[33])+(-k_E)*(y[34]);
 	 ydot[35] = (k_E)*(y[34])+(-k_I)*(y[35])+(k_PM_4)*(y[36]);
 	 ydot[36] = (k_I)*(y[35])+(-(k_PM_4+k_D))*(y[36]);
 	 ydot[37] = (-(k_I_lig*ligand))*(y[37])+(k_PM_4_lig*ligand)*(y[38]);
 	 ydot[38] = (k_I_lig*ligand)*(y[37])+(-(k_PM_4_lig*ligand+k_D_lig*ligand))*(y[38]);
 	 ydot[39] = (-(k_B+k_E/(1.0+k_IM_3*(y[3]+y[5]*ligand))))*(y[39])+(-(k_P*k_IM_1/pow((1.0+k_IM_1*(y[3]+y[5]*ligand)),2.0)-k_E*y[0]*k_IM_3/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(y[42])+(-(k_P*(k_IM_1*ligand)/pow((1.0+k_IM_1*(y[3]+y[5]*ligand)),2.0)-k_E*y[0]*(k_IM_3*ligand)/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(y[44]);
 	 ydot[40] = (k_E/(1.0+k_IM_3*(y[3]+y[5]*ligand)))*(y[39])+(-k_E)*(y[40])+(-(k_E*y[0]*k_IM_3/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(y[42])+(-(k_E*y[0]*(k_IM_3*ligand)/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(y[44]);
 	 ydot[41] = (k_E)*(y[40])+(-k_E)*(y[41]);
 	 ydot[42] = (k_E)*(y[41])+(-k_I)*(y[42])+(k_PM_4)*(y[43]);
 	 ydot[43] = (k_I)*(y[42])+(-(k_PM_4+k_D))*(y[43]);
 	 ydot[44] = (-(k_I_lig*ligand))*(y[44])+(k_PM_4_lig*ligand)*(y[45]);
 	 ydot[45] = (k_I_lig*ligand)*(y[44])+(-(k_PM_4_lig*ligand+k_D_lig*ligand))*(y[45]);
 	 ydot[46] = (-(k_B+k_E/(1.0+k_IM_3*(y[3]+y[5]*ligand))))*(y[46])+(-(k_P*k_IM_1/pow((1.0+k_IM_1*(y[3]+y[5]*ligand)),2.0)-k_E*y[0]*k_IM_3/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(y[49])+(-(k_P*(k_IM_1*ligand)/pow((1.0+k_IM_1*(y[3]+y[5]*ligand)),2.0)-k_E*y[0]*(k_IM_3*ligand)/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(0.0)+1.0/(1.0+k_IM_1*(y[3]+y[5]*ligand));
 	 ydot[47] = (k_E/(1.0+k_IM_3*(y[3]+y[5]*ligand)))*(y[46])+(-k_E)*(y[47])+(-(k_E*y[0]*k_IM_3/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(y[49])+(-(k_E*y[0]*(k_IM_3*ligand)/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(0.0);
 	 ydot[48] = (k_E)*(y[47])+(-k_E)*(y[48]);
 	 ydot[49] = (k_E)*(y[48])+(-k_I)*(y[49])+(k_PM_4)*(y[50]);
 	 ydot[50] = (k_I)*(y[49])+(-(k_PM_4+k_D))*(y[50]);
 	 ydot[51] = (-(k_B+k_E/(1.0+k_IM_3*(y[3]+y[5]*ligand))))*(y[51])+(-(k_P*k_IM_1/pow((1.0+k_IM_1*(y[3]+y[5]*ligand)),2.0)-k_E*y[0]*k_IM_3/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(y[54])+(-(k_P*(k_IM_1*ligand)/pow((1.0+k_IM_1*(y[3]+y[5]*ligand)),2.0)-k_E*y[0]*(k_IM_3*ligand)/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(0.0)-(k_P*(y[3]+y[5]*ligand)/pow((1.0+k_IM_1*(y[3]+y[5]*ligand)),2.0));
 	 ydot[52] = (k_E/(1.0+k_IM_3*(y[3]+y[5]*ligand)))*(y[51])+(-k_E)*(y[52])+(-(k_E*y[0]*k_IM_3/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(y[54])+(-(k_E*y[0]*(k_IM_3*ligand)/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(0.0);
 	 ydot[53] = (k_E)*(y[52])+(-k_E)*(y[53]);
 	 ydot[54] = (k_E)*(y[53])+(-k_I)*(y[54])+(k_PM_4)*(y[55]);
 	 ydot[55] = (k_I)*(y[54])+(-(k_PM_4+k_D))*(y[55]);
 	 ydot[56] = (-(k_B+k_E/(1.0+k_IM_3*(y[3]+y[5]*ligand))))*(y[56])+(-(k_P*k_IM_1/pow((1.0+k_IM_1*(y[3]+y[5]*ligand)),2.0)-k_E*y[0]*k_IM_3/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(y[59])+(-(k_P*(k_IM_1*ligand)/pow((1.0+k_IM_1*(y[3]+y[5]*ligand)),2.0)-k_E*y[0]*(k_IM_3*ligand)/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(y[61])-(k_P*(k_IM_1*y[5])/pow((1.0+k_IM_1*(y[3]+y[5]*ligand)),2.0)-k_E*y[0]*(k_IM_3*y[5])/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0));
 	 ydot[57] = (k_E/(1.0+k_IM_3*(y[3]+y[5]*ligand)))*(y[56])+(-k_E)*(y[57])+(-(k_E*y[0]*k_IM_3/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(y[59])+(-(k_E*y[0]*(k_IM_3*ligand)/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(y[61])-(k_E*y[0]*(k_IM_3*y[5])/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0));
 	 ydot[58] = (k_E)*(y[57])+(-k_E)*(y[58]);
 	 ydot[59] = (k_E)*(y[58])+(-k_I)*(y[59])+(k_PM_4)*(y[60]);
 	 ydot[60] = (k_I)*(y[59])+(-(k_PM_4+k_D))*(y[60]);
 	 ydot[61] = (-(k_I_lig*ligand))*(y[61])+(k_PM_4_lig*ligand)*(y[62])+k_PM_4_lig*y[6]-k_I_lig*y[5];
 	 ydot[62] = (k_I_lig*ligand)*(y[61])+(-(k_PM_4_lig*ligand+k_D_lig*ligand))*(y[62])+k_I_lig*y[5]-k_PM_4_lig*y[6]-k_D_lig*y[6];
 	 ydot[63] = (-(k_B+k_E/(1.0+k_IM_3*(y[3]+y[5]*ligand))))*(y[63])+(-(k_P*k_IM_1/pow((1.0+k_IM_1*(y[3]+y[5]*ligand)),2.0)-k_E*y[0]*k_IM_3/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(y[66])+(-(k_P*(k_IM_1*ligand)/pow((1.0+k_IM_1*(y[3]+y[5]*ligand)),2.0)-k_E*y[0]*(k_IM_3*ligand)/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(0.0)-y[0];
 	 ydot[64] = (k_E/(1.0+k_IM_3*(y[3]+y[5]*ligand)))*(y[63])+(-k_E)*(y[64])+(-(k_E*y[0]*k_IM_3/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(y[66])+(-(k_E*y[0]*(k_IM_3*ligand)/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(0.0);
 	 ydot[65] = (k_E)*(y[64])+(-k_E)*(y[65]);
 	 ydot[66] = (k_E)*(y[65])+(-k_I)*(y[66])+(k_PM_4)*(y[67]);
 	 ydot[67] = (k_I)*(y[66])+(-(k_PM_4+k_D))*(y[67]);
 	 ydot[68] = (-(k_B+k_E/(1.0+k_IM_3*(y[3]+y[5]*ligand))))*(y[68])+(-(k_P*k_IM_1/pow((1.0+k_IM_1*(y[3]+y[5]*ligand)),2.0)-k_E*y[0]*k_IM_3/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(y[71])+(-(k_P*(k_IM_1*ligand)/pow((1.0+k_IM_1*(y[3]+y[5]*ligand)),2.0)-k_E*y[0]*(k_IM_3*ligand)/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(0.0)-(y[0]/(1.0+k_IM_3*(y[3]+y[5]*ligand)));
 	 ydot[69] = (k_E/(1.0+k_IM_3*(y[3]+y[5]*ligand)))*(y[68])+(-k_E)*(y[69])+(-(k_E*y[0]*k_IM_3/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(y[71])+(-(k_E*y[0]*(k_IM_3*ligand)/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(0.0)+y[0]/(1.0+k_IM_3*(y[3]+y[5]*ligand))-y[1];
 	 ydot[70] = (k_E)*(y[69])+(-k_E)*(y[70])+y[1]-y[2];
 	 ydot[71] = (k_E)*(y[70])+(-k_I)*(y[71])+(k_PM_4)*(y[72])+y[2];
 	 ydot[72] = (k_I)*(y[71])+(-(k_PM_4+k_D))*(y[72]);
 	 ydot[73] = (-(k_B+k_E/(1.0+k_IM_3*(y[3]+y[5]*ligand))))*(y[73])+(-(k_P*k_IM_1/pow((1.0+k_IM_1*(y[3]+y[5]*ligand)),2.0)-k_E*y[0]*k_IM_3/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(y[76])+(-(k_P*(k_IM_1*ligand)/pow((1.0+k_IM_1*(y[3]+y[5]*ligand)),2.0)-k_E*y[0]*(k_IM_3*ligand)/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(0.0)+k_E*y[0]*(y[3]+y[5]*ligand)/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0);
 	 ydot[74] = (k_E/(1.0+k_IM_3*(y[3]+y[5]*ligand)))*(y[73])+(-k_E)*(y[74])+(-(k_E*y[0]*k_IM_3/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(y[76])+(-(k_E*y[0]*(k_IM_3*ligand)/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(0.0)-(k_E*y[0]*(y[3]+y[5]*ligand)/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0));
 	 ydot[75] = (k_E)*(y[74])+(-k_E)*(y[75]);
 	 ydot[76] = (k_E)*(y[75])+(-k_I)*(y[76])+(k_PM_4)*(y[77]);
 	 ydot[77] = (k_I)*(y[76])+(-(k_PM_4+k_D))*(y[77]);
 	 ydot[78] = (-(k_B+k_E/(1.0+k_IM_3*(y[3]+y[5]*ligand))))*(y[78])+(-(k_P*k_IM_1/pow((1.0+k_IM_1*(y[3]+y[5]*ligand)),2.0)-k_E*y[0]*k_IM_3/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(y[81])+(-(k_P*(k_IM_1*ligand)/pow((1.0+k_IM_1*(y[3]+y[5]*ligand)),2.0)-k_E*y[0]*(k_IM_3*ligand)/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(0.0);
 	 ydot[79] = (k_E/(1.0+k_IM_3*(y[3]+y[5]*ligand)))*(y[78])+(-k_E)*(y[79])+(-(k_E*y[0]*k_IM_3/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(y[81])+(-(k_E*y[0]*(k_IM_3*ligand)/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(0.0);
 	 ydot[80] = (k_E)*(y[79])+(-k_E)*(y[80]);
 	 ydot[81] = (k_E)*(y[80])+(-k_I)*(y[81])+(k_PM_4)*(y[82])-y[3];
 	 ydot[82] = (k_I)*(y[81])+(-(k_PM_4+k_D))*(y[82])+y[3];
 	 ydot[83] = (-(k_B+k_E/(1.0+k_IM_3*(y[3]+y[5]*ligand))))*(y[83])+(-(k_P*k_IM_1/pow((1.0+k_IM_1*(y[3]+y[5]*ligand)),2.0)-k_E*y[0]*k_IM_3/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(y[86])+(-(k_P*(k_IM_1*ligand)/pow((1.0+k_IM_1*(y[3]+y[5]*ligand)),2.0)-k_E*y[0]*(k_IM_3*ligand)/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(0.0);
 	 ydot[84] = (k_E/(1.0+k_IM_3*(y[3]+y[5]*ligand)))*(y[83])+(-k_E)*(y[84])+(-(k_E*y[0]*k_IM_3/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(y[86])+(-(k_E*y[0]*(k_IM_3*ligand)/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(0.0);
 	 ydot[85] = (k_E)*(y[84])+(-k_E)*(y[85]);
 	 ydot[86] = (k_E)*(y[85])+(-k_I)*(y[86])+(k_PM_4)*(y[87])+y[4];
 	 ydot[87] = (k_I)*(y[86])+(-(k_PM_4+k_D))*(y[87])-y[4];
 	 ydot[88] = (-(k_B+k_E/(1.0+k_IM_3*(y[3]+y[5]*ligand))))*(y[88])+(-(k_P*k_IM_1/pow((1.0+k_IM_1*(y[3]+y[5]*ligand)),2.0)-k_E*y[0]*k_IM_3/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(y[91])+(-(k_P*(k_IM_1*ligand)/pow((1.0+k_IM_1*(y[3]+y[5]*ligand)),2.0)-k_E*y[0]*(k_IM_3*ligand)/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(0.0);
 	 ydot[89] = (k_E/(1.0+k_IM_3*(y[3]+y[5]*ligand)))*(y[88])+(-k_E)*(y[89])+(-(k_E*y[0]*k_IM_3/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(y[91])+(-(k_E*y[0]*(k_IM_3*ligand)/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(0.0);
 	 ydot[90] = (k_E)*(y[89])+(-k_E)*(y[90]);
 	 ydot[91] = (k_E)*(y[90])+(-k_I)*(y[91])+(k_PM_4)*(y[92]);
 	 ydot[92] = (k_I)*(y[91])+(-(k_PM_4+k_D))*(y[92])-y[4];
 	 ydot[93] = (-(k_B+k_E/(1.0+k_IM_3*(y[3]+y[5]*ligand))))*(y[93])+(-(k_P*k_IM_1/pow((1.0+k_IM_1*(y[3]+y[5]*ligand)),2.0)-k_E*y[0]*k_IM_3/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(y[96])+(-(k_P*(k_IM_1*ligand)/pow((1.0+k_IM_1*(y[3]+y[5]*ligand)),2.0)-k_E*y[0]*(k_IM_3*ligand)/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(y[98]);
 	 ydot[94] = (k_E/(1.0+k_IM_3*(y[3]+y[5]*ligand)))*(y[93])+(-k_E)*(y[94])+(-(k_E*y[0]*k_IM_3/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(y[96])+(-(k_E*y[0]*(k_IM_3*ligand)/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(y[98]);
 	 ydot[95] = (k_E)*(y[94])+(-k_E)*(y[95]);
 	 ydot[96] = (k_E)*(y[95])+(-k_I)*(y[96])+(k_PM_4)*(y[97]);
 	 ydot[97] = (k_I)*(y[96])+(-(k_PM_4+k_D))*(y[97]);
 	 ydot[98] = (-(k_I_lig*ligand))*(y[98])+(k_PM_4_lig*ligand)*(y[99])-(y[5]*ligand);
 	 ydot[99] = (k_I_lig*ligand)*(y[98])+(-(k_PM_4_lig*ligand+k_D_lig*ligand))*(y[99])+y[5]*ligand;
 	 ydot[100] = (-(k_B+k_E/(1.0+k_IM_3*(y[3]+y[5]*ligand))))*(y[100])+(-(k_P*k_IM_1/pow((1.0+k_IM_1*(y[3]+y[5]*ligand)),2.0)-k_E*y[0]*k_IM_3/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(y[103])+(-(k_P*(k_IM_1*ligand)/pow((1.0+k_IM_1*(y[3]+y[5]*ligand)),2.0)-k_E*y[0]*(k_IM_3*ligand)/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(y[105]);
 	 ydot[101] = (k_E/(1.0+k_IM_3*(y[3]+y[5]*ligand)))*(y[100])+(-k_E)*(y[101])+(-(k_E*y[0]*k_IM_3/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(y[103])+(-(k_E*y[0]*(k_IM_3*ligand)/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(y[105]);
 	 ydot[102] = (k_E)*(y[101])+(-k_E)*(y[102]);
 	 ydot[103] = (k_E)*(y[102])+(-k_I)*(y[103])+(k_PM_4)*(y[104]);
 	 ydot[104] = (k_I)*(y[103])+(-(k_PM_4+k_D))*(y[104]);
 	 ydot[105] = (-(k_I_lig*ligand))*(y[105])+(k_PM_4_lig*ligand)*(y[106])+y[6]*ligand;
 	 ydot[106] = (k_I_lig*ligand)*(y[105])+(-(k_PM_4_lig*ligand+k_D_lig*ligand))*(y[106])-(y[6]*ligand);
 	 ydot[107] = (-(k_B+k_E/(1.0+k_IM_3*(y[3]+y[5]*ligand))))*(y[107])+(-(k_P*k_IM_1/pow((1.0+k_IM_1*(y[3]+y[5]*ligand)),2.0)-k_E*y[0]*k_IM_3/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(y[110])+(-(k_P*(k_IM_1*ligand)/pow((1.0+k_IM_1*(y[3]+y[5]*ligand)),2.0)-k_E*y[0]*(k_IM_3*ligand)/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(y[112]);
 	 ydot[108] = (k_E/(1.0+k_IM_3*(y[3]+y[5]*ligand)))*(y[107])+(-k_E)*(y[108])+(-(k_E*y[0]*k_IM_3/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(y[110])+(-(k_E*y[0]*(k_IM_3*ligand)/pow((1.0+k_IM_3*(y[3]+y[5]*ligand)),2.0)))*(y[112]);
 	 ydot[109] = (k_E)*(y[108])+(-k_E)*(y[109]);
 	 ydot[110] = (k_E)*(y[109])+(-k_I)*(y[110])+(k_PM_4)*(y[111]);
 	 ydot[111] = (k_I)*(y[110])+(-(k_PM_4+k_D))*(y[111]);
 	 ydot[112] = (-(k_I_lig*ligand))*(y[112])+(k_PM_4_lig*ligand)*(y[113]);
 	 ydot[113] = (k_I_lig*ligand)*(y[112])+(-(k_PM_4_lig*ligand+k_D_lig*ligand))*(y[113])-(y[6]*ligand);

	 for(int i=  0 ; i <  26 ; ++i) RPAR[i] = 0;
}

