/** Code auto-generated by cOde 1.1.1 **/
#include <R.h> 
 #include <math.h> 

static double parms[75];
static double forc[0];
static double cons[0];
static double range[2];

#define nGridpoints 2 
#define nSplines 0 
#define precision 1e-05 

#define k_P parms[0] 
 #define k_IM_1 parms[1] 
 #define ligand parms[2] 
 #define k_B parms[3] 
 #define k_I parms[4] 
 #define k_PM_4 parms[5] 
 #define k_B_lig parms[6] 
 #define k_I_lig parms[7] 
 #define k_PM_4_lig parms[8] 
 #define k_D parms[9] 
 #define k_D_lig parms[10] 
 #define y0_0 parms[11] 
 #define y1_0 parms[12] 
 #define y2_0 parms[13] 
 #define y3_0 parms[14] 
 #define y4_0 parms[15] 
 #define y5_0 parms[16] 
 #define y6_0 parms[17] 
 #define y7_0 parms[18] 
 #define y8_0 parms[19] 
 #define y9_0 parms[20] 
 #define y10_0 parms[21] 
 #define y11_0 parms[22] 
 #define y12_0 parms[23] 
 #define y13_0 parms[24] 
 #define y14_0 parms[25] 
 #define y15_0 parms[26] 
 #define y16_0 parms[27] 
 #define y17_0 parms[28] 
 #define y18_0 parms[29] 
 #define y19_0 parms[30] 
 #define y20_0 parms[31] 
 #define y21_0 parms[32] 
 #define y22_0 parms[33] 
 #define y23_0 parms[34] 
 #define y24_0 parms[35] 
 #define y25_0 parms[36] 
 #define y26_0 parms[37] 
 #define y27_0 parms[38] 
 #define y28_0 parms[39] 
 #define y29_0 parms[40] 
 #define y30_0 parms[41] 
 #define y31_0 parms[42] 
 #define y32_0 parms[43] 
 #define y33_0 parms[44] 
 #define y34_0 parms[45] 
 #define y35_0 parms[46] 
 #define y36_0 parms[47] 
 #define y37_0 parms[48] 
 #define y38_0 parms[49] 
 #define y39_0 parms[50] 
 #define y40_0 parms[51] 
 #define y41_0 parms[52] 
 #define y42_0 parms[53] 
 #define y43_0 parms[54] 
 #define y44_0 parms[55] 
 #define y45_0 parms[56] 
 #define y46_0 parms[57] 
 #define y47_0 parms[58] 
 #define y48_0 parms[59] 
 #define y49_0 parms[60] 
 #define y50_0 parms[61] 
 #define y51_0 parms[62] 
 #define y52_0 parms[63] 
 #define y53_0 parms[64] 
 #define y54_0 parms[65] 
 #define y55_0 parms[66] 
 #define y56_0 parms[67] 
 #define y57_0 parms[68] 
 #define y58_0 parms[69] 
 #define y59_0 parms[70] 
 #define y60_0 parms[71] 
 #define y61_0 parms[72] 
 #define y62_0 parms[73] 
 #define y63_0 parms[74] 
#define tmin range[0]
#define tmax range[1]


void x_s_initmod(void (* odeparms)(int *, double *)) {
	 int N=75;
	 odeparms(&N, parms);
}

void x_s_initforc(void (* odeforcs)(int *, double *)) {
	 int N=0;
	 odeforcs(&N, forc);
}

/** Derivatives (ODE system) **/
void x_s_derivs (int *n, double *t, double *y, double *ydot, double *RPAR, int *IPAR) {

	 double time = *t;

	 ydot[0] = 1.0*(k_P/(1.0+k_IM_1*(y[0]+y[1]*ligand)))-1.0*(k_B*y[0])-1.0*(k_I*y[0])+1.0*(k_PM_4*(y[0]+y[1]*ligand)*y[2]);
 	 ydot[1] = -1.0*(k_B_lig*y[1]*ligand)-1.0*(k_I_lig*y[1]*ligand)+1.0*(k_PM_4_lig*(y[1]+y[0])*y[3]*ligand);
 	 ydot[2] = 1.0*(k_I*y[0])-1.0*(k_PM_4*(y[0]+y[1]*ligand)*y[2])-1.0*(k_D*y[2]);
 	 ydot[3] = 1.0*(k_I_lig*y[1]*ligand)-1.0*(k_PM_4_lig*(y[1]+y[0])*y[3]*ligand)-1.0*(k_D_lig*y[3]*ligand);
 	 ydot[4] = (k_PM_4*y[2]-(k_P*k_IM_1/pow((1.0+k_IM_1*(y[0]+y[1]*ligand)),2.0)+k_B+k_I))*(y[4])+(k_PM_4*ligand*y[2]-k_P*(k_IM_1*ligand)/pow((1.0+k_IM_1*(y[0]+y[1]*ligand)),2.0))*(y[5])+(k_PM_4*(y[0]+y[1]*ligand))*(y[6]);
 	 ydot[5] = (k_PM_4_lig*y[3]*ligand)*(y[4])+(k_PM_4_lig*y[3]*ligand-(k_B_lig*ligand+k_I_lig*ligand))*(y[5])+(k_PM_4_lig*(y[1]+y[0])*ligand)*(y[7]);
 	 ydot[6] = (k_I-k_PM_4*y[2])*(y[4])+(-(k_PM_4*ligand*y[2]))*(y[5])+(-(k_PM_4*(y[0]+y[1]*ligand)+k_D))*(y[6]);
 	 ydot[7] = (-(k_PM_4_lig*y[3]*ligand))*(y[4])+(k_I_lig*ligand-k_PM_4_lig*y[3]*ligand)*(y[5])+(-(k_PM_4_lig*(y[1]+y[0])*ligand+k_D_lig*ligand))*(y[7]);
 	 ydot[8] = (k_PM_4*y[2]-(k_P*k_IM_1/pow((1.0+k_IM_1*(y[0]+y[1]*ligand)),2.0)+k_B+k_I))*(y[8])+(k_PM_4*ligand*y[2]-k_P*(k_IM_1*ligand)/pow((1.0+k_IM_1*(y[0]+y[1]*ligand)),2.0))*(y[9])+(k_PM_4*(y[0]+y[1]*ligand))*(y[10]);
 	 ydot[9] = (k_PM_4_lig*y[3]*ligand)*(y[8])+(k_PM_4_lig*y[3]*ligand-(k_B_lig*ligand+k_I_lig*ligand))*(y[9])+(k_PM_4_lig*(y[1]+y[0])*ligand)*(y[11]);
 	 ydot[10] = (k_I-k_PM_4*y[2])*(y[8])+(-(k_PM_4*ligand*y[2]))*(y[9])+(-(k_PM_4*(y[0]+y[1]*ligand)+k_D))*(y[10]);
 	 ydot[11] = (-(k_PM_4_lig*y[3]*ligand))*(y[8])+(k_I_lig*ligand-k_PM_4_lig*y[3]*ligand)*(y[9])+(-(k_PM_4_lig*(y[1]+y[0])*ligand+k_D_lig*ligand))*(y[11]);
 	 ydot[12] = (k_PM_4*y[2]-(k_P*k_IM_1/pow((1.0+k_IM_1*(y[0]+y[1]*ligand)),2.0)+k_B+k_I))*(y[12])+(k_PM_4*ligand*y[2]-k_P*(k_IM_1*ligand)/pow((1.0+k_IM_1*(y[0]+y[1]*ligand)),2.0))*(y[13])+(k_PM_4*(y[0]+y[1]*ligand))*(y[14]);
 	 ydot[13] = (k_PM_4_lig*y[3]*ligand)*(y[12])+(k_PM_4_lig*y[3]*ligand-(k_B_lig*ligand+k_I_lig*ligand))*(y[13])+(k_PM_4_lig*(y[1]+y[0])*ligand)*(y[15]);
 	 ydot[14] = (k_I-k_PM_4*y[2])*(y[12])+(-(k_PM_4*ligand*y[2]))*(y[13])+(-(k_PM_4*(y[0]+y[1]*ligand)+k_D))*(y[14]);
 	 ydot[15] = (-(k_PM_4_lig*y[3]*ligand))*(y[12])+(k_I_lig*ligand-k_PM_4_lig*y[3]*ligand)*(y[13])+(-(k_PM_4_lig*(y[1]+y[0])*ligand+k_D_lig*ligand))*(y[15]);
 	 ydot[16] = (k_PM_4*y[2]-(k_P*k_IM_1/pow((1.0+k_IM_1*(y[0]+y[1]*ligand)),2.0)+k_B+k_I))*(y[16])+(k_PM_4*ligand*y[2]-k_P*(k_IM_1*ligand)/pow((1.0+k_IM_1*(y[0]+y[1]*ligand)),2.0))*(y[17])+(k_PM_4*(y[0]+y[1]*ligand))*(y[18]);
 	 ydot[17] = (k_PM_4_lig*y[3]*ligand)*(y[16])+(k_PM_4_lig*y[3]*ligand-(k_B_lig*ligand+k_I_lig*ligand))*(y[17])+(k_PM_4_lig*(y[1]+y[0])*ligand)*(y[19]);
 	 ydot[18] = (k_I-k_PM_4*y[2])*(y[16])+(-(k_PM_4*ligand*y[2]))*(y[17])+(-(k_PM_4*(y[0]+y[1]*ligand)+k_D))*(y[18]);
 	 ydot[19] = (-(k_PM_4_lig*y[3]*ligand))*(y[16])+(k_I_lig*ligand-k_PM_4_lig*y[3]*ligand)*(y[17])+(-(k_PM_4_lig*(y[1]+y[0])*ligand+k_D_lig*ligand))*(y[19]);
 	 ydot[20] = (k_PM_4*y[2]-(k_P*k_IM_1/pow((1.0+k_IM_1*(y[0]+y[1]*ligand)),2.0)+k_B+k_I))*(y[20])+(k_PM_4*ligand*y[2]-k_P*(k_IM_1*ligand)/pow((1.0+k_IM_1*(y[0]+y[1]*ligand)),2.0))*(y[21])+(k_PM_4*(y[0]+y[1]*ligand))*(y[22])+1.0/(1.0+k_IM_1*(y[0]+y[1]*ligand));
 	 ydot[21] = (k_PM_4_lig*y[3]*ligand)*(y[20])+(k_PM_4_lig*y[3]*ligand-(k_B_lig*ligand+k_I_lig*ligand))*(y[21])+(k_PM_4_lig*(y[1]+y[0])*ligand)*(y[23]);
 	 ydot[22] = (k_I-k_PM_4*y[2])*(y[20])+(-(k_PM_4*ligand*y[2]))*(y[21])+(-(k_PM_4*(y[0]+y[1]*ligand)+k_D))*(y[22]);
 	 ydot[23] = (-(k_PM_4_lig*y[3]*ligand))*(y[20])+(k_I_lig*ligand-k_PM_4_lig*y[3]*ligand)*(y[21])+(-(k_PM_4_lig*(y[1]+y[0])*ligand+k_D_lig*ligand))*(y[23]);
 	 ydot[24] = (k_PM_4*y[2]-(k_P*k_IM_1/pow((1.0+k_IM_1*(y[0]+y[1]*ligand)),2.0)+k_B+k_I))*(y[24])+(k_PM_4*ligand*y[2]-k_P*(k_IM_1*ligand)/pow((1.0+k_IM_1*(y[0]+y[1]*ligand)),2.0))*(y[25])+(k_PM_4*(y[0]+y[1]*ligand))*(y[26])-(k_P*(y[0]+y[1]*ligand)/pow((1.0+k_IM_1*(y[0]+y[1]*ligand)),2.0));
 	 ydot[25] = (k_PM_4_lig*y[3]*ligand)*(y[24])+(k_PM_4_lig*y[3]*ligand-(k_B_lig*ligand+k_I_lig*ligand))*(y[25])+(k_PM_4_lig*(y[1]+y[0])*ligand)*(y[27]);
 	 ydot[26] = (k_I-k_PM_4*y[2])*(y[24])+(-(k_PM_4*ligand*y[2]))*(y[25])+(-(k_PM_4*(y[0]+y[1]*ligand)+k_D))*(y[26]);
 	 ydot[27] = (-(k_PM_4_lig*y[3]*ligand))*(y[24])+(k_I_lig*ligand-k_PM_4_lig*y[3]*ligand)*(y[25])+(-(k_PM_4_lig*(y[1]+y[0])*ligand+k_D_lig*ligand))*(y[27]);
 	 ydot[28] = (k_PM_4*y[2]-(k_P*k_IM_1/pow((1.0+k_IM_1*(y[0]+y[1]*ligand)),2.0)+k_B+k_I))*(y[28])+(k_PM_4*ligand*y[2]-k_P*(k_IM_1*ligand)/pow((1.0+k_IM_1*(y[0]+y[1]*ligand)),2.0))*(y[29])+(k_PM_4*(y[0]+y[1]*ligand))*(y[30])+k_PM_4*y[1]*y[2]-k_P*(k_IM_1*y[1])/pow((1.0+k_IM_1*(y[0]+y[1]*ligand)),2.0);
 	 ydot[29] = (k_PM_4_lig*y[3]*ligand)*(y[28])+(k_PM_4_lig*y[3]*ligand-(k_B_lig*ligand+k_I_lig*ligand))*(y[29])+(k_PM_4_lig*(y[1]+y[0])*ligand)*(y[31])+k_PM_4_lig*(y[1]+y[0])*y[3]-(k_B_lig*y[1]+k_I_lig*y[1]);
 	 ydot[30] = (k_I-k_PM_4*y[2])*(y[28])+(-(k_PM_4*ligand*y[2]))*(y[29])+(-(k_PM_4*(y[0]+y[1]*ligand)+k_D))*(y[30])-(k_PM_4*y[1]*y[2]);
 	 ydot[31] = (-(k_PM_4_lig*y[3]*ligand))*(y[28])+(k_I_lig*ligand-k_PM_4_lig*y[3]*ligand)*(y[29])+(-(k_PM_4_lig*(y[1]+y[0])*ligand+k_D_lig*ligand))*(y[31])+k_I_lig*y[1]-k_PM_4_lig*(y[1]+y[0])*y[3]-k_D_lig*y[3];
 	 ydot[32] = (k_PM_4*y[2]-(k_P*k_IM_1/pow((1.0+k_IM_1*(y[0]+y[1]*ligand)),2.0)+k_B+k_I))*(y[32])+(k_PM_4*ligand*y[2]-k_P*(k_IM_1*ligand)/pow((1.0+k_IM_1*(y[0]+y[1]*ligand)),2.0))*(y[33])+(k_PM_4*(y[0]+y[1]*ligand))*(y[34])-y[0];
 	 ydot[33] = (k_PM_4_lig*y[3]*ligand)*(y[32])+(k_PM_4_lig*y[3]*ligand-(k_B_lig*ligand+k_I_lig*ligand))*(y[33])+(k_PM_4_lig*(y[1]+y[0])*ligand)*(y[35]);
 	 ydot[34] = (k_I-k_PM_4*y[2])*(y[32])+(-(k_PM_4*ligand*y[2]))*(y[33])+(-(k_PM_4*(y[0]+y[1]*ligand)+k_D))*(y[34]);
 	 ydot[35] = (-(k_PM_4_lig*y[3]*ligand))*(y[32])+(k_I_lig*ligand-k_PM_4_lig*y[3]*ligand)*(y[33])+(-(k_PM_4_lig*(y[1]+y[0])*ligand+k_D_lig*ligand))*(y[35]);
 	 ydot[36] = (k_PM_4*y[2]-(k_P*k_IM_1/pow((1.0+k_IM_1*(y[0]+y[1]*ligand)),2.0)+k_B+k_I))*(y[36])+(k_PM_4*ligand*y[2]-k_P*(k_IM_1*ligand)/pow((1.0+k_IM_1*(y[0]+y[1]*ligand)),2.0))*(y[37])+(k_PM_4*(y[0]+y[1]*ligand))*(y[38])-y[0];
 	 ydot[37] = (k_PM_4_lig*y[3]*ligand)*(y[36])+(k_PM_4_lig*y[3]*ligand-(k_B_lig*ligand+k_I_lig*ligand))*(y[37])+(k_PM_4_lig*(y[1]+y[0])*ligand)*(y[39]);
 	 ydot[38] = (k_I-k_PM_4*y[2])*(y[36])+(-(k_PM_4*ligand*y[2]))*(y[37])+(-(k_PM_4*(y[0]+y[1]*ligand)+k_D))*(y[38])+y[0];
 	 ydot[39] = (-(k_PM_4_lig*y[3]*ligand))*(y[36])+(k_I_lig*ligand-k_PM_4_lig*y[3]*ligand)*(y[37])+(-(k_PM_4_lig*(y[1]+y[0])*ligand+k_D_lig*ligand))*(y[39]);
 	 ydot[40] = (k_PM_4*y[2]-(k_P*k_IM_1/pow((1.0+k_IM_1*(y[0]+y[1]*ligand)),2.0)+k_B+k_I))*(y[40])+(k_PM_4*ligand*y[2]-k_P*(k_IM_1*ligand)/pow((1.0+k_IM_1*(y[0]+y[1]*ligand)),2.0))*(y[41])+(k_PM_4*(y[0]+y[1]*ligand))*(y[42])+(y[0]+y[1]*ligand)*y[2];
 	 ydot[41] = (k_PM_4_lig*y[3]*ligand)*(y[40])+(k_PM_4_lig*y[3]*ligand-(k_B_lig*ligand+k_I_lig*ligand))*(y[41])+(k_PM_4_lig*(y[1]+y[0])*ligand)*(y[43]);
 	 ydot[42] = (k_I-k_PM_4*y[2])*(y[40])+(-(k_PM_4*ligand*y[2]))*(y[41])+(-(k_PM_4*(y[0]+y[1]*ligand)+k_D))*(y[42])-((y[0]+y[1]*ligand)*y[2]);
 	 ydot[43] = (-(k_PM_4_lig*y[3]*ligand))*(y[40])+(k_I_lig*ligand-k_PM_4_lig*y[3]*ligand)*(y[41])+(-(k_PM_4_lig*(y[1]+y[0])*ligand+k_D_lig*ligand))*(y[43]);
 	 ydot[44] = (k_PM_4*y[2]-(k_P*k_IM_1/pow((1.0+k_IM_1*(y[0]+y[1]*ligand)),2.0)+k_B+k_I))*(y[44])+(k_PM_4*ligand*y[2]-k_P*(k_IM_1*ligand)/pow((1.0+k_IM_1*(y[0]+y[1]*ligand)),2.0))*(y[45])+(k_PM_4*(y[0]+y[1]*ligand))*(y[46]);
 	 ydot[45] = (k_PM_4_lig*y[3]*ligand)*(y[44])+(k_PM_4_lig*y[3]*ligand-(k_B_lig*ligand+k_I_lig*ligand))*(y[45])+(k_PM_4_lig*(y[1]+y[0])*ligand)*(y[47])-(y[1]*ligand);
 	 ydot[46] = (k_I-k_PM_4*y[2])*(y[44])+(-(k_PM_4*ligand*y[2]))*(y[45])+(-(k_PM_4*(y[0]+y[1]*ligand)+k_D))*(y[46]);
 	 ydot[47] = (-(k_PM_4_lig*y[3]*ligand))*(y[44])+(k_I_lig*ligand-k_PM_4_lig*y[3]*ligand)*(y[45])+(-(k_PM_4_lig*(y[1]+y[0])*ligand+k_D_lig*ligand))*(y[47]);
 	 ydot[48] = (k_PM_4*y[2]-(k_P*k_IM_1/pow((1.0+k_IM_1*(y[0]+y[1]*ligand)),2.0)+k_B+k_I))*(y[48])+(k_PM_4*ligand*y[2]-k_P*(k_IM_1*ligand)/pow((1.0+k_IM_1*(y[0]+y[1]*ligand)),2.0))*(y[49])+(k_PM_4*(y[0]+y[1]*ligand))*(y[50]);
 	 ydot[49] = (k_PM_4_lig*y[3]*ligand)*(y[48])+(k_PM_4_lig*y[3]*ligand-(k_B_lig*ligand+k_I_lig*ligand))*(y[49])+(k_PM_4_lig*(y[1]+y[0])*ligand)*(y[51])-(y[1]*ligand);
 	 ydot[50] = (k_I-k_PM_4*y[2])*(y[48])+(-(k_PM_4*ligand*y[2]))*(y[49])+(-(k_PM_4*(y[0]+y[1]*ligand)+k_D))*(y[50]);
 	 ydot[51] = (-(k_PM_4_lig*y[3]*ligand))*(y[48])+(k_I_lig*ligand-k_PM_4_lig*y[3]*ligand)*(y[49])+(-(k_PM_4_lig*(y[1]+y[0])*ligand+k_D_lig*ligand))*(y[51])+y[1]*ligand;
 	 ydot[52] = (k_PM_4*y[2]-(k_P*k_IM_1/pow((1.0+k_IM_1*(y[0]+y[1]*ligand)),2.0)+k_B+k_I))*(y[52])+(k_PM_4*ligand*y[2]-k_P*(k_IM_1*ligand)/pow((1.0+k_IM_1*(y[0]+y[1]*ligand)),2.0))*(y[53])+(k_PM_4*(y[0]+y[1]*ligand))*(y[54]);
 	 ydot[53] = (k_PM_4_lig*y[3]*ligand)*(y[52])+(k_PM_4_lig*y[3]*ligand-(k_B_lig*ligand+k_I_lig*ligand))*(y[53])+(k_PM_4_lig*(y[1]+y[0])*ligand)*(y[55])+(y[1]+y[0])*y[3]*ligand;
 	 ydot[54] = (k_I-k_PM_4*y[2])*(y[52])+(-(k_PM_4*ligand*y[2]))*(y[53])+(-(k_PM_4*(y[0]+y[1]*ligand)+k_D))*(y[54]);
 	 ydot[55] = (-(k_PM_4_lig*y[3]*ligand))*(y[52])+(k_I_lig*ligand-k_PM_4_lig*y[3]*ligand)*(y[53])+(-(k_PM_4_lig*(y[1]+y[0])*ligand+k_D_lig*ligand))*(y[55])-((y[1]+y[0])*y[3]*ligand);
 	 ydot[56] = (k_PM_4*y[2]-(k_P*k_IM_1/pow((1.0+k_IM_1*(y[0]+y[1]*ligand)),2.0)+k_B+k_I))*(y[56])+(k_PM_4*ligand*y[2]-k_P*(k_IM_1*ligand)/pow((1.0+k_IM_1*(y[0]+y[1]*ligand)),2.0))*(y[57])+(k_PM_4*(y[0]+y[1]*ligand))*(y[58]);
 	 ydot[57] = (k_PM_4_lig*y[3]*ligand)*(y[56])+(k_PM_4_lig*y[3]*ligand-(k_B_lig*ligand+k_I_lig*ligand))*(y[57])+(k_PM_4_lig*(y[1]+y[0])*ligand)*(y[59]);
 	 ydot[58] = (k_I-k_PM_4*y[2])*(y[56])+(-(k_PM_4*ligand*y[2]))*(y[57])+(-(k_PM_4*(y[0]+y[1]*ligand)+k_D))*(y[58])-y[2];
 	 ydot[59] = (-(k_PM_4_lig*y[3]*ligand))*(y[56])+(k_I_lig*ligand-k_PM_4_lig*y[3]*ligand)*(y[57])+(-(k_PM_4_lig*(y[1]+y[0])*ligand+k_D_lig*ligand))*(y[59]);
 	 ydot[60] = (k_PM_4*y[2]-(k_P*k_IM_1/pow((1.0+k_IM_1*(y[0]+y[1]*ligand)),2.0)+k_B+k_I))*(y[60])+(k_PM_4*ligand*y[2]-k_P*(k_IM_1*ligand)/pow((1.0+k_IM_1*(y[0]+y[1]*ligand)),2.0))*(y[61])+(k_PM_4*(y[0]+y[1]*ligand))*(y[62]);
 	 ydot[61] = (k_PM_4_lig*y[3]*ligand)*(y[60])+(k_PM_4_lig*y[3]*ligand-(k_B_lig*ligand+k_I_lig*ligand))*(y[61])+(k_PM_4_lig*(y[1]+y[0])*ligand)*(y[63]);
 	 ydot[62] = (k_I-k_PM_4*y[2])*(y[60])+(-(k_PM_4*ligand*y[2]))*(y[61])+(-(k_PM_4*(y[0]+y[1]*ligand)+k_D))*(y[62]);
 	 ydot[63] = (-(k_PM_4_lig*y[3]*ligand))*(y[60])+(k_I_lig*ligand-k_PM_4_lig*y[3]*ligand)*(y[61])+(-(k_PM_4_lig*(y[1]+y[0])*ligand+k_D_lig*ligand))*(y[63])-(y[3]*ligand);

}

